name: qudris_shopkeeper
description: POS & inventory for shops
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.1+2

environment:
  sdk: ^3.9.0

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.5.1
  
  # Navigation
  go_router: ^16.2.1
  
  # Supabase Backend
  supabase_flutter: ^2.5.0
  
  # Local Database (Offline-First)
  drift: ^2.15.0
  drift_sqflite: ^2.0.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.1.4
  path: ^1.9.0
  
  # HTTP & Networking
  dio: ^5.4.0
  http: ^1.1.0
  connectivity_plus: ^7.0.0
  
  # Code Generation
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.0
  
  # Device & Platform
  device_info_plus: ^10.0.0
  shared_preferences: ^2.2.0
  
  # UI & Scanning
  mobile_scanner: ^7.0.1
  qr_flutter: ^4.1.0
  
  # Utilities
  intl: ^0.20.2
  uuid: ^4.0.0
  
  # Security & Storage
  flutter_secure_storage: ^9.2.2
  permission_handler: ^12.0.1
  share_plus: ^10.0.0
  
  # Legacy (to be phased out after migration)
  google_sign_in: ^6.1.6
  googleapis: ^14.0.0
  googleapis_auth: ^2.0.0
  crypto: ^3.0.3
  cryptography: ^2.7.0
  
  # Other
  cupertino_icons: ^1.0.8
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Generation
  build_runner: ^2.4.11
  drift_dev: ^2.15.0
  json_serializable: ^6.9.0
  freezed: ^2.4.0
  
  # Linting
  flutter_lints: ^6.0.0
  
  # Testing
  mockito: ^5.4.0
  
  # App Icons & Splash
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/icons/app_icon1.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

# App Icons (Launcher)
flutter_launcher_icons:
  android: true
  ios: false            # leave false for now; we'll enable later if needed
  image_path: assets/icons/app_icon1.png
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: assets/icons/app_icon1.png
  remove_alpha_ios: true

# Splash Screen
flutter_native_splash:
  android: true
  ios: false            # keep false for now
  image: assets/icons/app_icon1.png
  color: "#FFFFFF"      # splash background; adjust as desired
  android_12:
    image: assets/icons/app_icon1.png
    color: "#FFFFFF"
